/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as BooksImport } from './routes/books'

// Create/Update Routes

const BooksRoute = BooksImport.update({
  path: '/books',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/books': typeof BooksRoute
}

export interface FileRoutesByTo {
  '/books': typeof BooksRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/books': typeof BooksRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/books'
  fileRoutesByTo: FileRoutesByTo
  to: '/books'
  id: '__root__' | '/books'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  BooksRoute: typeof BooksRoute
}

const rootRouteChildren: RootRouteChildren = {
  BooksRoute: BooksRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/books"
      ]
    },
    "/books": {
      "filePath": "books.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
